"""created reply functionality

Revision ID: 4e9e305806fc
Revises: 65c51dc2f2ff
Create Date: 2024-10-08 00:04:08.384605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e9e305806fc'
down_revision = '65c51dc2f2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('reply_to_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('reply_to_user_id', sa.Integer(), nullable=True))
    op.drop_column('messages', 'reply_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'reply_to_user_id')
    op.drop_column('messages', 'reply_to_content')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
