"""added message reactions

Revision ID: 65c51dc2f2ff
Revises: 1732d14412d1
Create Date: 2024-10-04 23:54:09.502276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65c51dc2f2ff'
down_revision = '1732d14412d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reactions')
    # ### end Alembic commands ###
