"""6

Revision ID: 953b1d3340e7
Revises: 97582766cf65
Create Date: 2024-09-21 12:44:08.768309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '953b1d3340e7'
down_revision = '97582766cf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chats_user_id'), table_name='user_chats')
    op.drop_index(op.f('ix_user_chats_id'), table_name='user_chats')
    op.drop_table('user_chats')
    # ### end Alembic commands ###
